name: Build IP CIDR Processor

on: 
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests pyyaml
        
    - name: Build executable
      run: |
        pyinstaller --onefile --name ip_cidr_processor_${{ matrix.os }} src/ip_cidr_processor.py
        ls -la dist/
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ip_cidr_processor_${{ matrix.os }}_py${{ matrix.python-version }}
        path: dist/ip_cidr_processor_${{ matrix.os }}*
        if-no-files-found: error
        retention-days: 5
